services:
  n8n-server:
    build:
      context: ./.
      dockerfile: Dockerfile
    image: n8n-server
    container_name: n8n-server
    restart: always
    environment:
      # Configuración de N8N
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=yourdomain.com
      # - N8N_PORT=5678
      - WEBHOOK_URL=https://yourdomain.com
      - N8N_PROTOCOL=https
      - GENERIC_TIMEZONE=America/Santiago
      - VIRTUAL_HOST=yourdomain.com
      - VIRTUAL_PORT=5678
      - N8N_SECURE_COOKIE=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_HIRING_BANNER_SHOWN=true
      - N8N_PERSONALIZATION_ENABLED=true
      - N8N_FEATURE_FLAGS=folders,workflowHistory,advancedDebugging,executionTags
      - N8N_LICENSE_KEY=yourkey
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      # Configuración para PostgreSQL
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=yourdatabase
      - DB_POSTGRESDB_USER=admin_db
      - DB_POSTGRESDB_PASSWORD=dbpassword
      # Config Headers Multipart
      - CLIENT_MAX_BODY_SIZE=50m
      - PROXY_REQUEST_BUFFERING=off
      - PROXY_READ_TIMEOUT=600s
      - PROXY_SEND_TIMEOUT=600s
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - n8n-network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin_db
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=yourdatabase
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - n8n-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_db -d yourdatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge
